apiVersion: cog.os/v1
kind: Site
metadata:
  name: myrgic-dev
spec:
  domain: myrgic.dev
  canonical: false
  source:
    path: src/
  build:
    command: ./build.sh
    dist: dist/
  https:
    required: true
  deploy:
    strategy: gh-pages
    target:
      repo: myrgic/myrgic.dev
  redirect_to: https://myrgic.com/
